name: deploy-model-server
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - with:
          SPELL_AUTH: ${{ secrets.SPELL_AUTH }}
        shell: bash
        run: ls